apiVersion: toolkit.ardikabs.com/v1alpha1
kind: HelmRelease
metadata:
  name: test-1
  namespace: default
  annotations:
    config.kubernetes.io/function: |
      container:
        image: ghcr.io/ardikabs/helmize:latest
        network: true # network enabled, because it is required for pulling from external chart
spec:
  chart: minecraft
  repo:
    name: minecraft
    url: https://itzg.github.io/minecraft-server-charts
