before:
  hooks:
    - go mod tidy

builds:
  - binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    ldflags:
      - -X github.com/ardikabs/{{ .ProjectName }}/cmd.Version={{.Version}}
      - -X github.com/ardikabs/{{ .ProjectName }}/cmd.GitCommit={{.Commit}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: binary

changelog:
  filters:
    exclude:
      - "^Release version"
      - "^Merge pull request"

checksum:
  name_template: "checksums.txt"

dockers:
  - goos: linux
    goarch: amd64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/ardikabs/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/ardikabs/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/ardikabs/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

  - goos: linux
    goarch: arm64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/ardikabs/{{ .ProjectName }}:latest-arm64"
      - "ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}-arm64"
      - "ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/ardikabs/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/ardikabs/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  - name_template: ghcr.io/ardikabs/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/ardikabs/{{ .ProjectName }}:latest-amd64
      - ghcr.io/ardikabs/{{ .ProjectName }}:latest-arm64
  - name_template: ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}
    image_templates:
      - ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}-amd64
      - ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}-arm64
  - name_template: ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64
  - name_template: ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - ghcr.io/ardikabs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64
