apiVersion: toolkit.ardikabs.com/v1alpha1
kind: HelmRelease
metadata:
  name: test-2
  namespace: default
  annotations:
    config.kubernetes.io/function: |
      exec:
        # path: helmize
        path: ../../bin/helmize
spec:
  chart: minecraft
  repo:
    name: minecraft
    url: https://itzg.github.io/minecraft-server-charts
  version: 3.1.4
  values:
    - release-2/values.yaml
