apiVersion: toolkit.ardikabs.com/v1alpha1
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
  annotations:
    config.kubernetes.io/function: |
      exec:
        # path: helmize
        path: ../../../bin/helmize
spec:
  repo:
    url: oci://docker.io/envoyproxy/gateway-helm
  version: v0.5.0
  includeCRDs: true
  createNamespace: true
