apiVersion: toolkit.ardikabs.com/v1alpha1
kind: HelmRelease
metadata:
  name: service-a
  namespace: default
  annotations:
    config.kubernetes.io/function: |
      exec:
        # path: helmize
        path: ../../../bin/helmize
spec:
  chart: common-app
  repo:
    name: ardikabs
    url: https://charts.ardikabs.com
  version: 0.4.1
  values:
    - values.yaml
    - values.d/*.yaml
    - values.d/enabled/*.yaml
