name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21.x

      - name: Get Tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.2
        with:
          strip_v: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.tag.outputs.tag }}
